In [63]:
from selenium import webdriver
import os
import warnings

os.environ['PATH'] += 'C:\Driver\chromedriver.exe'

warnings.filterwarnings("ignore",category=DeprecationWarning)

driver = webdriver.Chrome(executable_path='C:\Driver\chromedriver.exe')

In [64]:
driver.get('https://www.linkedin.com/jobs/search/?geoId=102257491&keywords=teaching&location=London%2C%20England%2C%20United%20Kingdom')
driver.implicitly_wait(5)

In [65]:
try:
    x = driver.find_element_by_xpath('//button[@class="cta-modal__dismiss-btn"]')
    x.click()
except:
    print('ok')

In [66]:
data_list = []

In [67]:
for i in range(1,20):
    temp_list = []
    element = driver.find_element_by_xpath(f'//div[@data-row="{i}"] | //a[@data-row="{i}"]')
    link = driver.find_element_by_xpath(f'(//div[@data-row="{i}"]/a[@class="base-card__full-link"]) | //a[@data-row="{i}"]')
    title = driver.find_element_by_xpath(f'(//div[@data-row="{i}"]//h3[@class="base-search-card__title"]) | //a[@data-row="{i}"]//h3[@class="base-search-card__title"]')
    company = driver.find_element_by_xpath(f'(//div[@data-row="{i}"]//h4[@class="base-search-card__subtitle"]) | //a[@data-row="{i}"]//h4[@class="base-search-card__subtitle"]')
    location = driver.find_element_by_xpath(f'(//div[@data-row="{i}"]//span[@class="job-search-card__location"]) | //a[@data-row="{i}"]//span[@class="job-search-card__location"]')
    time_element = driver.find_element_by_xpath(f'(//div[@data-row="{i}"]//time) | //a[@data-row="{i}"]//time')
    temp_list.append(title.text)
    temp_list.append(company.text)
    temp_list.append(location.text)
    temp_list.append(time_element.get_attribute('datetime'))
    temp_list.append(link.get_attribute('href'))
    data_list.append(temp_list)

In [70]:
data_list

[['Teaching Assistant',
  'Vibe Teaching',
  'London, England, United Kingdom',
  '2022-04-21',
  'https://uk.linkedin.com/jobs/view/teaching-assistant-at-vibe-teaching-3037623043?refId=iUhkMIUyaArR9dBAliVmFQ%3D%3D&trackingId=PkOYuZeXS%2BM0znL0ch6xuQ%3D%3D&position=1&pageNum=0&trk=public_jobs_jserp-result_search-card'],
 ['Hourly Paid Teacher',
  'British Council',
  'London, England, United Kingdom',
  '2022-04-08',
  'https://uk.linkedin.com/jobs/view/hourly-paid-teacher-at-british-council-3010658803?refId=iUhkMIUyaArR9dBAliVmFQ%3D%3D&trackingId=JmZdbcXd9LxvZOZj7Syo%2FQ%3D%3D&position=2&pageNum=0&trk=public_jobs_jserp-result_search-card'],
 ['Primary School Teacher',
  'Opogo',
  'London, England, United Kingdom',
  '2022-04-05',
  'https://uk.linkedin.com/jobs/view/primary-school-teacher-at-opogo-3005927906?refId=iUhkMIUyaArR9dBAliVmFQ%3D%3D&trackingId=NWw9EWzYNxciCaYieMkHyQ%3D%3D&position=3&pageNum=0&trk=public_jobs_jserp-result_search-card'],
 ['Teacher of Spanish',
  'E-ACT Crest Academy',
  'London, England, United Kingdom',
  '2022-03-21',
  'https://uk.linkedin.com/jobs/view/teacher-of-spanish-at-e-act-crest-academy-3030283610?refId=iUhkMIUyaArR9dBAliVmFQ%3D%3D&trackingId=amj1Amt53OAGe5NFEAtdWg%3D%3D&position=4&pageNum=0&trk=public_jobs_jserp-result_search-card'],
 ['Primary School Teacher',
  'Vibe Teaching',
  'London, England, United Kingdom',
  '2021-11-09',
  'https://uk.linkedin.com/jobs/view/primary-school-teacher-at-vibe-teaching-2768874241?refId=iUhkMIUyaArR9dBAliVmFQ%3D%3D&trackingId=SRH9nR5S%2F86%2B4wKQvWoHGA%3D%3D&position=5&pageNum=0&trk=public_jobs_jserp-result_search-card'],
 ['Teacher of Academic Projects',
  "King's College London Mathematics School",
  'London, England, United Kingdom',
  '2022-04-15',
  'https://uk.linkedin.com/jobs/view/teacher-of-academic-projects-at-king-s-college-london-mathematics-school-3028044438?refId=iUhkMIUyaArR9dBAliVmFQ%3D%3D&trackingId=l9dk2867NCdcBrCDtHKjTA%3D%3D&position=6&pageNum=0&trk=public_jobs_jserp-result_search-card'],
 ['Student Success Advisor',
  'Pearson',
  'London, England, United Kingdom',
  '2022-03-13',
  'https://uk.linkedin.com/jobs/view/student-success-advisor-at-pearson-3008981696?refId=iUhkMIUyaArR9dBAliVmFQ%3D%3D&trackingId=TvptmpSHMc5KYwWD2ZYLOw%3D%3D&position=7&pageNum=0&trk=public_jobs_jserp-result_search-card'],
 ['Primary Teacher',
  'n',
  'London, England, United Kingdom',
  '2022-04-21',
  'https://uk.linkedin.com/jobs/view/primary-teacher-at-n-3038369560?refId=iUhkMIUyaArR9dBAliVmFQ%3D%3D&trackingId=0XKHCyCk0gdFCvZQcCH1ZA%3D%3D&position=8&pageNum=0&trk=public_jobs_jserp-result_search-card'],
 ['English Teacher',
  'The London Teaching Pool',
  'London, England, United Kingdom',
  '2022-04-20',
  'https://uk.linkedin.com/jobs/view/english-teacher-at-the-london-teaching-pool-3035998324?refId=iUhkMIUyaArR9dBAliVmFQ%3D%3D&trackingId=EJ%2FkdtBRFWcs%2FXYXfORyyA%3D%3D&position=9&pageNum=0&trk=public_jobs_jserp-result_search-card'],
 ['Teacher',
  'St. Jérôme Church of England Bilingual School',
  'London, England, United Kingdom',
  '2022-04-06',
  'https://uk.linkedin.com/jobs/view/teacher-at-st-j%C3%A9r%C3%B4me-church-of-england-bilingual-school-3011758242?refId=iUhkMIUyaArR9dBAliVmFQ%3D%3D&trackingId=lzchvIq12I5pJhF6mYjn9Q%3D%3D&position=10&pageNum=0&trk=public_jobs_jserp-result_search-card'],
 ['Teacher',
  'STEP Academy Trust',
  'Bromley, England, United Kingdom',
  '2022-04-07',
  'https://uk.linkedin.com/jobs/view/teacher-at-step-academy-trust-3014051719?refId=iUhkMIUyaArR9dBAliVmFQ%3D%3D&trackingId=QJ5rU4jv2G1hDB4jUldqmg%3D%3D&position=11&pageNum=0&trk=public_jobs_jserp-result_search-card'],
 ['Teaching Assistant',
  'Blackfen',
  'London, England, United Kingdom',
  '2022-04-02',
  'https://uk.linkedin.com/jobs/view/teaching-assistant-at-blackfen-3002797460?refId=iUhkMIUyaArR9dBAliVmFQ%3D%3D&trackingId=LwhQkoBoi8ynb1786sAARA%3D%3D&position=12&pageNum=0&trk=public_jobs_jserp-result_search-card'],
 ['Tutor',
  'Tutor Doctor Greenwich',
  'London, England, United Kingdom',
  '2022-04-20',
  'https://uk.linkedin.com/jobs/view/tutor-at-tutor-doctor-greenwich-3035934913?refId=iUhkMIUyaArR9dBAliVmFQ%3D%3D&trackingId=p1SsBtvhQQlvIMGePay7fA%3D%3D&position=13&pageNum=0&trk=public_jobs_jserp-result_search-card'],
 ['Teaching Assistant - Camden',
  'Academics Ltd',
  'London, England, United Kingdom',
  '2022-04-21',
  'https://uk.linkedin.com/jobs/view/teaching-assistant-camden-at-academics-ltd-3038334151?refId=iUhkMIUyaArR9dBAliVmFQ%3D%3D&trackingId=vHq%2BpDCc%2B04Qw%2FIVEzs7WQ%3D%3D&position=14&pageNum=0&trk=public_jobs_jserp-result_search-card'],
 ['Support Officer (Student and Teaching)',
  'The London School of Economics and Political Science (LSE)',
  'London, England, United Kingdom',
  '2022-04-11',
  'https://uk.linkedin.com/jobs/view/support-officer-student-and-teaching-at-the-london-school-of-economics-and-political-science-lse-2976504965?refId=iUhkMIUyaArR9dBAliVmFQ%3D%3D&trackingId=%2B2s4gRbHNYsdMyQShlrxug%3D%3D&position=15&pageNum=0&trk=public_jobs_jserp-result_search-card'],
 ['Teaching Assistant',
  'The Kingston Academy',
  'Kingston upon Thames, England, United Kingdom',
  '2022-03-30',
  'https://uk.linkedin.com/jobs/view/teaching-assistant-at-the-kingston-academy-2998409614?refId=iUhkMIUyaArR9dBAliVmFQ%3D%3D&trackingId=dmdAW1xuDM4Sh%2FvvgHnm7A%3D%3D&position=16&pageNum=0&trk=public_jobs_jserp-result_search-card'],
 ['Teachers',
  'Clarus Education',
  'London, England, United Kingdom',
  '2022-04-05',
  'https://uk.linkedin.com/jobs/view/teachers-at-clarus-education-3009870733?refId=iUhkMIUyaArR9dBAliVmFQ%3D%3D&trackingId=ZgHyqxMrXce1UQmS6FwKOQ%3D%3D&position=17&pageNum=0&trk=public_jobs_jserp-result_search-card'],
 ['International School Teachers',
  'Equal Education Partners',
  'London, England, United Kingdom',
  '2022-03-24',
  'https://uk.linkedin.com/jobs/view/international-school-teachers-at-equal-education-partners-3031015430?refId=iUhkMIUyaArR9dBAliVmFQ%3D%3D&trackingId=TTCcJ71bRi4e%2Ba7we0Cwhw%3D%3D&position=18&pageNum=0&trk=public_jobs_jserp-result_search-card'],
 ['Primary Teaching Assistant',
  'ASQ Education',
  'London, England, United Kingdom',
  '2022-03-30',
  'https://uk.linkedin.com/jobs/view/primary-teaching-assistant-at-asq-education-2992795447?refId=iUhkMIUyaArR9dBAliVmFQ%3D%3D&trackingId=hwyd%2FSRcRJ0lWiVc1OLgWw%3D%3D&position=19&pageNum=0&trk=public_jobs_jserp-result_search-card']]

In [71]:
import pandas as pd

In [72]:
df = pd.DataFrame(columns=['Title','Company','Location','Time','Link'],data=data_list)

In [73]:
df

,Title,Company,Location,Time,Link
0,Teaching Assistant,Vibe Teaching,"London, England, United Kingdom",2022-04-21,https://uk.linkedin.com/jobs/view/teaching-ass...
1,Hourly Paid Teacher,British Council,"London, England, United Kingdom",2022-04-08,https://uk.linkedin.com/jobs/view/hourly-paid-...
2,Primary School Teacher,Opogo,"London, England, United Kingdom",2022-04-05,https://uk.linkedin.com/jobs/view/primary-scho...
3,Teacher of Spanish,E-ACT Crest Academy,"London, England, United Kingdom",2022-03-21,https://uk.linkedin.com/jobs/view/teacher-of-s...
4,Primary School Teacher,Vibe Teaching,"London, England, United Kingdom",2021-11-09,https://uk.linkedin.com/jobs/view/primary-scho...
5,Teacher of Academic Projects,King's College London Mathematics School,"London, England, United Kingdom",2022-04-15,https://uk.linkedin.com/jobs/view/teacher-of-a...
6,Student Success Advisor,Pearson,"London, England, United Kingdom",2022-03-13,https://uk.linkedin.com/jobs/view/student-succ...
7,Primary Teacher,n,"London, England, United Kingdom",2022-04-21,https://uk.linkedin.com/jobs/view/primary-teac...
8,English Teacher,The London Teaching Pool,"London, England, United Kingdom",2022-04-20,https://uk.linkedin.com/jobs/view/english-teac...
9,Teacher,St. Jérôme Church of England Bilingual School,"London, England, United Kingdom",2022-04-06,https://uk.linkedin.com/jobs/view/teacher-at-s...
10,Teacher,STEP Academy Trust,"Bromley, England, United Kingdom",2022-04-07,https://uk.linkedin.com/jobs/view/teacher-at-s...
11,Teaching Assistant,Blackfen,"London, England, United Kingdom",2022-04-02,https://uk.linkedin.com/jobs/view/teaching-ass...
12,Tutor,Tutor Doctor Greenwich,"London, England, United Kingdom",2022-04-20,https://uk.linkedin.com/jobs/view/tutor-at-tut...
13,Teaching Assistant - Camden,Academics Ltd,"London, England, United Kingdom",2022-04-21,https://uk.linkedin.com/jobs/view/teaching-ass...
14,Support Officer (Student and Teaching),The London School of Economics and Political S...,"London, England, United Kingdom",2022-04-11,https://uk.linkedin.com/jobs/view/support-offi...
15,Teaching Assistant,The Kingston Academy,"Kingston upon Thames, England, United Kingdom",2022-03-30,https://uk.linkedin.com/jobs/view/teaching-ass...
16,Teachers,Clarus Education,"London, England, United Kingdom",2022-04-05,https://uk.linkedin.com/jobs/view/teachers-at-...
17,International School Teachers,Equal Education Partners,"London, England, United Kingdom",2022-03-24,https://uk.linkedin.com/jobs/view/internationa...
18,Primary Teaching Assistant,ASQ Education,"London, England, United Kingdom",2022-03-30,https://uk.linkedin.com/jobs/view/primary-teac...

In [58]:
df.to_csv('up.csv')